name: Run Python Script Every Hour

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the version of Python you need

    - name: Run Script
      run: |
        python3 main.py  # Adjust the path to your script
